function sectionDatasetInfo = ImportSectionDatasetGeneMapping(fileName)
% Script for importing data from the following text file:
%
%    /Users/benfulcher/GoogleDrive/Work/CurrentProjects/Timescales_Wang/Code/AllenSDK/sectionDatasetInfo.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2016/11/16 19:25:58

%% Initialize variables.
if nargin < 1
    fileName = 'sectionDatasetInfo.csv';
end
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(fileName,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
sectionDatasetInfo = table(dataArray{1:end-1}, 'VariableNames', {'entrez_id','plane_of_section_id','section_id'});
